name: CI/CD for MERN Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Frontend Docker Image
        run: docker build -t your-dockerhub-anaseg/banking-application:latest -f frontend/Dockerfile .

      - name: Build Backend Docker Image
        run: docker build -t your-dockerhub-anaseg/banking-application:latest -f backend/Dockerfile .

      - name: Push Frontend Image to Docker Hub
        run: docker push your-dockerhub-anaseg/banking-application:latest

      - name: Push Backend Image to Docker Hub
        run: docker push your-dockerhub-anaseg/banking-application:latest
