name: Deploy Bank Application

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u${{ secrets.DOCKER_USERNAME }} -p  ${{ secrets.DOCKER_PASSWORD}}
